version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'Deps'
    groups:
      dev-dependencies:
        dependency-type: 'development'
