services:
  frontend:
    image: project-template-frontend:dev
    build:
      dockerfile: ./apps/frontend/Dockerfile
      context: .
      target: dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/frontend/node_modules
      - /app/apps/frontend/.next

  backend:
    image: project-template-backend:dev
    build:
      dockerfile: ./apps/backend/Dockerfile
      context: .
      target: dev
    ports:
      - '9229:9229'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/backend/node_modules

  package-builder:
    image: project-template-package-builder:dev
    build:
      dockerfile: ./packages/Dockerfile
      context: .
    volumes:
      - ./packages:/app/packages
