services:
  frontend:
    restart: unless-stopped
    build:
      dockerfile: ./apps/frontend/Dockerfile
      context: .
      target: prod
    ports:
      - '80:3000'

  backend:
    restart: unless-stopped
    build:
      dockerfile: ./apps/backend/Dockerfile
      context: .
      target: prod
