services:
  frontend:
    build:
      dockerfile: ./services/frontend/Dockerfile
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/services/frontend/node_modules
    environment:
      - VITE_BACKEND_URL=/api
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING:-false}

  backend:
    build:
      dockerfile: ./services/backend/Dockerfile
      context: .
      target: dev
    ports:
      - '9229:9229'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/services/backend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING:-false}

  package-builder:
    build:
      dockerfile: ./packages/Dockerfile
      context: .
    volumes:
      - ./packages:/app/packages
    environment:
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING:-false}

  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: ./services/nginx/Dockerfile.dev
      context: .
    ports:
      - '80:80'
