version: '3.8'

services:
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build: ./services/nginx
    ports:
      - '80:80'

  frontend:
    build:
      dockerfile: ./services/frontend/Dockerfile
      context: .
    volumes:
      - ./services/frontend:/app/services/frontend
      - /app/services/frontend/node_modules # Vite cache
    environment:
      - VITE_BACKEND_URL=/api
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}

  backend:
    build:
      dockerfile: ./services/backend/Dockerfile
      context: .
    ports:
      - '9229:9229'
    volumes:
      - ./services/backend:/app/services/backend
    environment:
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
