version: '3.8'

services:
  frontend:
    build:
      dockerfile: ./services/frontend/Dockerfile.dev
      context: .
    volumes:
      - ./services/frontend:/app/services/frontend
      - ./packages/some-package/dist:/app/packages/some-package/dist
    environment:
      - VITE_BACKEND_URL=/api
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING:-false}

  backend:
    build:
      dockerfile: ./services/backend/Dockerfile.dev
      context: .
    ports:
      - '9229:9229'
    volumes:
      - ./services/backend:/app/services/backend
      - ./packages/some-package/dist:/app/packages/some-package/dist
    environment:
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING:-false}

  package-builder:
    build:
      dockerfile: ./services/package-builder/Dockerfile.dev
      context: .
    volumes:
      - ./packages:/app/packages
    environment:
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING:-false}

  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: ./services/nginx/Dockerfile.dev
      context: .
    ports:
      - '80:80'
