version: '3.8'

services:
  frontend:
    build:
      context: ./services/frontend
    ports:
      - '5173:5173'
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:8000

  backend:
    build:
      context: ./services/backend
    ports:
      - '8000:8000'
      - '9229:9229'
    volumes:
      - ./services/backend:/app
      - /app/node_modules
