version: '3.8'

services:
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build: ./services/nginx
    ports:
      - '80:80'

  frontend:
    build:
      context: ./services/frontend
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=/backend
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}

  backend:
    build:
      context: ./services/backend
    ports:
      - '9229:9229'
    volumes:
      - ./services/backend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
