FROM node:18.13.0-alpine3.17 as builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:18.13.0-alpine3.17

ENV NODE_PATH=dist/
ENV NODE_ENV=production
ENV PORT=80

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist

EXPOSE 80
CMD ["npm", "start"]