ARG SERVICE_NAME=backend

FROM node:20.15.1-alpine3.20 as base
ARG SERVICE_NAME
ENV SERVICE_NAME ${SERVICE_NAME}

WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.json \
  .eslintrc.json .prettierrc ./
COPY packages packages
COPY services/$SERVICE_NAME/package.json services/$SERVICE_NAME/
RUN find packages \! -name "package.json" -mindepth 2 -maxdepth 2 -print | \
  xargs rm -rf

FROM node:20.15.1-alpine3.20
ARG SERVICE_NAME
ENV SERVICE_NAME ${SERVICE_NAME}

WORKDIR /app
COPY --from=base /app ./
RUN corepack enable pnpm && pnpm install

USER node
CMD pnpm -F ${SERVICE_NAME} run dev