FROM node:20.12.0-alpine3.19 as base

WORKDIR /app
COPY package*.json tsconfig.json .eslintrc.json .prettierrc ./
COPY packages packages
RUN find ./packages -mindepth 2 \( ! -name 'package.json' \) -delete 2>/dev/null

FROM node:20.12.0-alpine3.19

WORKDIR /app
COPY --from=base /app ./
RUN npm install

USER node
CMD ["./packages/run-all.sh", "build:watch"]
