FROM node:18.17.0-alpine3.18 as base

WORKDIR /app
COPY package*.json tsconfig.json .eslintrc.json .prettierrc ./
COPY patches patches
COPY packages packages
RUN find ./packages -mindepth 2 \( ! -name 'package.json' \) -delete 2>/dev/null

FROM node:18.17.0-alpine3.18

WORKDIR /app
COPY --from=base /app ./
RUN npm install

USER node
CMD ["./packages/run-all.sh", "build:watch"]
