ARG SERVICE_NAME=frontend

FROM node:20.12.0-alpine3.19 as base
ARG SERVICE_NAME
ENV SERVICE_NAME ${SERVICE_NAME}

WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.json \
  .eslintrc.json .prettierrc ./
COPY packages packages
COPY services/$SERVICE_NAME/package.json services/$SERVICE_NAME/
RUN find packages \! -name "package.json" -mindepth 2 -maxdepth 2 -print | \
  xargs rm -rf

FROM node:20.12.0-alpine3.19
ARG SERVICE_NAME
ENV SERVICE_NAME ${SERVICE_NAME}

WORKDIR /app
COPY --from=base /app ./
RUN corepack enable pnpm && pnpm install

# https://www.reddit.com/r/docker/comments/ww6rt5/comment/ir7jndi/
RUN mkdir /app/node_modules/.vite && \
  chown -R node:node /app/node_modules/.vite

USER node
CMD pnpm -F ${SERVICE_NAME} run dev
